// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as Twind from "twind";
import * as Printf from "bs-platform/lib/es6/printf.js";
import Link from "next/link";
import * as Belt_Array from "bs-platform/lib/es6/belt_Array.js";

function Board(Props) {
  var isFallback = Props.isFallback;
  var posts = Props.posts;
  var tmp;
  if (isFallback) {
    tmp = React.createElement("div", undefined, "Loading...");
  } else {
    var tmp$1;
    tmp$1 = posts.TAG === /* Ok */0 ? React.createElement("ul", {
            className: Twind.tw("list-disc")
          }, Belt_Array.map(posts._0, (function (post) {
                  var key = post.bid + "/" + post.aid;
                  var href = Curry._2(Printf.sprintf({
                            _0: {
                              TAG: 11,
                              _0: "/post/",
                              _1: {
                                TAG: 2,
                                _0: /* No_padding */0,
                                _1: {
                                  TAG: 12,
                                  _0: /* '/' */47,
                                  _1: {
                                    TAG: 2,
                                    _0: /* No_padding */0,
                                    _1: /* End_of_format */0,
                                    [Symbol.for("name")]: "String"
                                  },
                                  [Symbol.for("name")]: "Char_literal"
                                },
                                [Symbol.for("name")]: "String"
                              },
                              [Symbol.for("name")]: "String_literal"
                            },
                            _1: "/post/%s/%s",
                            [Symbol.for("name")]: "Format"
                          }), post.bid, post.aid);
                  return React.createElement("li", {
                              key: key
                            }, React.createElement(Link, {
                                  href: href,
                                  children: post.title
                                }));
                }))) : React.createElement("div", undefined, posts._0);
    tmp = React.createElement(React.Fragment, undefined, tmp$1);
  }
  return React.createElement("div", undefined, tmp);
}

var make = Board;

export {
  make ,
  
}
/* react Not a pure module */
