// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import Head from "next/head";

function Meta(Props) {
  var titleOpt = Props.title;
  var title = titleOpt !== undefined ? titleOpt : "Ptt";
  return React.createElement(Head, {
              children: null
            }, React.createElement("title", {
                  key: "title"
                }, title), React.createElement("meta", {
                  charSet: "utf-8"
                }), React.createElement("meta", {
                  content: "width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1, minimal-ui",
                  name: "viewport"
                }));
}

var Head$1;

var make = Meta;

export {
  Head$1 as Head,
  make ,
  
}
/* react Not a pure module */
