// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function Post(Props) {
  var data = Props.data;
  var comments = Props.comments;
  return React.createElement("div", undefined, React.createElement("div", undefined, data.brdname), React.createElement("h1", undefined, data.class, data.title), React.createElement("ul", {
                  className: "list-decimal"
                }, comments.map(function (comment) {
                      return React.createElement("li", {
                                  key: comment.cid
                                }, comment.content.map(function (content) {
                                      return React.createElement("div", undefined, content.map(function (content) {
                                                        return content.text;
                                                      }).join(" "));
                                    }));
                    })));
}

var make = Post;

export {
  make ,
  
}
/* react Not a pure module */
