// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as Printf from "bs-platform/lib/es6/printf.js";
import Link from "next/link";

function TrendingBoards(Props) {
  var data = Props.data;
  return React.createElement("div", undefined, React.createElement("ul", {
                  className: "list-disc"
                }, data.map(function (board) {
                      var key = board.bid;
                      var href = Curry._1(Printf.sprintf({
                                _0: {
                                  TAG: 11,
                                  _0: "/post/",
                                  _1: {
                                    TAG: 2,
                                    _0: /* No_padding */0,
                                    _1: /* End_of_format */0,
                                    [Symbol.for("name")]: "String"
                                  },
                                  [Symbol.for("name")]: "String_literal"
                                },
                                _1: "/post/%s",
                                [Symbol.for("name")]: "Format"
                              }), board.bid);
                      return React.createElement("li", {
                                  key: key
                                }, React.createElement(Link, {
                                      href: href,
                                      children: board.brdname
                                    }));
                    })));
}

var make = TrendingBoards;

export {
  make ,
  
}
/* react Not a pure module */
