// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as TrendingPosts from "./TrendingPosts.js";

function $$default(param) {
  return React.createElement(TrendingPosts.make, {});
}

export {
  $$default ,
  $$default as default,
  
}
/* react Not a pure module */
