// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Api from "./common/Api.js";
import * as Post from "./components/Post.js";
import * as React from "react";
import * as $$Promise from "@ryyppy/rescript-promise/src/Promise.js";
import * as Js_option from "bs-platform/lib/es6/js_option.js";
import * as Belt_Result from "bs-platform/lib/es6/belt_Result.js";
import * as Router from "next/router";

function $$default(props) {
  var router = Router.useRouter();
  return React.createElement(Post.make, {
              isFallback: router.isFallback,
              post: props.post,
              comments: props.comments
            });
}

function getStaticProps(ctx) {
  var params = ctx.params;
  return $$Promise.$$catch(Promise.all([
                        Api.getPost(params.board, params.slug),
                        Api.getComment(params.board, params.slug)
                      ]).then(function (res) {
                      return Promise.all([
                                  res[0].json(),
                                  res[1].json()
                                ]);
                    }).then(function (json) {
                    return Promise.resolve({
                                TAG: 0,
                                _0: [
                                  ((json) => json)(json[0]),
                                  ((json) => json["list"])(json[1])
                                ],
                                [Symbol.for("name")]: "Ok"
                              });
                  }), (function (e) {
                  return Promise.resolve({
                              TAG: 1,
                              _0: e.RE_EXN_ID === $$Promise.JsError ? Js_option.getWithDefault("", e._1.message) : "Unexpected error occurred",
                              [Symbol.for("name")]: "Error"
                            });
                })).then(function (results) {
              return Promise.resolve({
                          props: {
                            post: Belt_Result.map(results, (function (prim) {
                                    return prim[0];
                                  })),
                            comments: Belt_Result.map(results, (function (prim) {
                                    return prim[1];
                                  }))
                          }
                        });
            });
}

function getStaticPaths(_params) {
  return Promise.resolve({
              paths: [],
              fallback: true
            });
}

export {
  $$default ,
  $$default as default,
  getStaticPaths ,
  getStaticProps ,
  
}
/* Post Not a pure module */
