// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function TrendingPosts(Props) {
  return React.createElement("div", undefined, "Trending Posts");
}

var make = TrendingPosts;

export {
  make ,
  
}
/* react Not a pure module */
