// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";
import * as Utils from "./Utils.js";
import * as Config from "./Config.js";
import * as Printf from "bs-platform/lib/es6/printf.js";

function makeEndpoint(endpoint) {
  return Curry._2(Printf.sprintf({
                  _0: {
                    TAG: 2,
                    _0: /* No_padding */0,
                    _1: {
                      TAG: 2,
                      _0: /* No_padding */0,
                      _1: /* End_of_format */0,
                      [Symbol.for("name")]: "String"
                    },
                    [Symbol.for("name")]: "String"
                  },
                  _1: "%s%s",
                  [Symbol.for("name")]: "Format"
                }), Utils.removeTrailingSlash(Config.getApiUrl(undefined)), endpoint);
}

function getHotPosts(limitOpt, sortOpt, param) {
  var limit = limitOpt !== undefined ? limitOpt : 3;
  var sort = sortOpt !== undefined ? sortOpt : /* Desc */1;
  return fetch(Curry._3(Printf.sprintf({
                      _0: {
                        TAG: 2,
                        _0: /* No_padding */0,
                        _1: {
                          TAG: 11,
                          _0: "?limit=",
                          _1: {
                            TAG: 4,
                            _0: /* Int_d */0,
                            _1: /* No_padding */0,
                            _2: /* No_precision */0,
                            _3: {
                              TAG: 11,
                              _0: "&desc=",
                              _1: {
                                TAG: 2,
                                _0: /* No_padding */0,
                                _1: /* End_of_format */0,
                                [Symbol.for("name")]: "String"
                              },
                              [Symbol.for("name")]: "String_literal"
                            },
                            [Symbol.for("name")]: "Int"
                          },
                          [Symbol.for("name")]: "String_literal"
                        },
                        [Symbol.for("name")]: "String"
                      },
                      _1: "%s?limit=%d&desc=%s",
                      [Symbol.for("name")]: "Format"
                    }), makeEndpoint("/api/articles/popular"), limit, sort === /* Desc */1 ? "true" : "false"));
}

export {
  makeEndpoint ,
  getHotPosts ,
  
}
/* No side effect */
