// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";
import * as Config from "./Config.js";
import * as Printf from "bs-platform/lib/es6/printf.js";

function getHotPosts(limitOpt, sortOpt, param) {
  var limit = limitOpt !== undefined ? limitOpt : 3;
  var sort = sortOpt !== undefined ? sortOpt : /* Desc */1;
  return fetch(Curry._3(Printf.sprintf({
                      _0: {
                        TAG: 2,
                        _0: /* No_padding */0,
                        _1: {
                          TAG: 11,
                          _0: "/api/articles/popular?limit=",
                          _1: {
                            TAG: 4,
                            _0: /* Int_d */0,
                            _1: /* No_padding */0,
                            _2: /* No_precision */0,
                            _3: {
                              TAG: 11,
                              _0: "&desc=",
                              _1: {
                                TAG: 2,
                                _0: /* No_padding */0,
                                _1: /* End_of_format */0,
                                [Symbol.for("name")]: "String"
                              },
                              [Symbol.for("name")]: "String_literal"
                            },
                            [Symbol.for("name")]: "Int"
                          },
                          [Symbol.for("name")]: "String_literal"
                        },
                        [Symbol.for("name")]: "String"
                      },
                      _1: "%s/api/articles/popular?limit=%d&desc=%s",
                      [Symbol.for("name")]: "Format"
                    }), Config.getApiUrl(undefined), limit, sort === /* Desc */1 ? "true" : "false"));
}

function getHotBoards(param) {
  return fetch(Curry._1(Printf.sprintf({
                      _0: {
                        TAG: 2,
                        _0: /* No_padding */0,
                        _1: {
                          TAG: 11,
                          _0: "/api/boards/popular",
                          _1: /* End_of_format */0,
                          [Symbol.for("name")]: "String_literal"
                        },
                        [Symbol.for("name")]: "String"
                      },
                      _1: "%s/api/boards/popular",
                      [Symbol.for("name")]: "Format"
                    }), Config.getApiUrl(undefined)));
}

function getPost(boardId, postId) {
  return fetch(Curry._3(Printf.sprintf({
                      _0: {
                        TAG: 2,
                        _0: /* No_padding */0,
                        _1: {
                          TAG: 11,
                          _0: "/api/board/",
                          _1: {
                            TAG: 2,
                            _0: /* No_padding */0,
                            _1: {
                              TAG: 11,
                              _0: "/article/",
                              _1: {
                                TAG: 2,
                                _0: /* No_padding */0,
                                _1: /* End_of_format */0,
                                [Symbol.for("name")]: "String"
                              },
                              [Symbol.for("name")]: "String_literal"
                            },
                            [Symbol.for("name")]: "String"
                          },
                          [Symbol.for("name")]: "String_literal"
                        },
                        [Symbol.for("name")]: "String"
                      },
                      _1: "%s/api/board/%s/article/%s",
                      [Symbol.for("name")]: "Format"
                    }), Config.getApiUrl(undefined), boardId, postId));
}

function getComment(boardId, postId) {
  return fetch(Curry._3(Printf.sprintf({
                      _0: {
                        TAG: 2,
                        _0: /* No_padding */0,
                        _1: {
                          TAG: 11,
                          _0: "/api/board/",
                          _1: {
                            TAG: 2,
                            _0: /* No_padding */0,
                            _1: {
                              TAG: 11,
                              _0: "/article/",
                              _1: {
                                TAG: 2,
                                _0: /* No_padding */0,
                                _1: {
                                  TAG: 11,
                                  _0: "/comments",
                                  _1: /* End_of_format */0,
                                  [Symbol.for("name")]: "String_literal"
                                },
                                [Symbol.for("name")]: "String"
                              },
                              [Symbol.for("name")]: "String_literal"
                            },
                            [Symbol.for("name")]: "String"
                          },
                          [Symbol.for("name")]: "String_literal"
                        },
                        [Symbol.for("name")]: "String"
                      },
                      _1: "%s/api/board/%s/article/%s/comments",
                      [Symbol.for("name")]: "Format"
                    }), Config.getApiUrl(undefined), boardId, postId));
}

export {
  getHotPosts ,
  getHotBoards ,
  getPost ,
  getComment ,
  
}
/* No side effect */
