// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_Option from "bs-platform/lib/es6/belt_Option.js";
import * as Caml_option from "bs-platform/lib/es6/caml_option.js";

function getApiUrl(param) {
  return Belt_Option.getWithDefault(Caml_option.undefined_to_opt(process.env.NEXT_PUBLIC_API), "<`NEXT_PUBLIC_API` is unset>");
}

export {
  getApiUrl ,
  
}
/* No side effect */
