// Generated by ReScript, PLEASE EDIT WITH CARE


var Sort = {};

var Board = {};

var Post = {};

var Content = {};

var $$Comment = {};

export {
  Sort ,
  Board ,
  Post ,
  Content ,
  $$Comment ,
  
}
/* No side effect */
