// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Meta from "../components/Meta.js";
import * as React from "react";
import * as Twind from "twind";
import Link from "next/link";

function MainLayout$Navigation(Props) {
  return React.createElement("nav", {
              className: Twind.tw("p-2", "h-12", "flex", "border-b", "border-gray-200", "justify-between", "items-center", "text-sm")
            }, React.createElement(Link, {
                  href: "/",
                  children: React.createElement("a", {
                        className: Twind.tw("flex", "items-center", "w-1/3")
                      }, React.createElement("span", {
                            className: Twind.tw("text-xl", "ml-2", "align-middle", "font-semibold")
                          }, "PTT"))
                }), React.createElement("div", {
                  className: Twind.tw("flex", "w-2/3", "justify-end")
                }, React.createElement(Link, {
                      href: "/",
                      children: React.createElement("a", {
                            className: Twind.tw("px-3")
                          }, "Home")
                    }), React.createElement(Link, {
                      href: "/trending/boards",
                      children: React.createElement("a", {
                            className: Twind.tw("px-3")
                          }, "Trending Boards")
                    }), React.createElement("a", {
                      className: Twind.tw("px-3", "font-bold"),
                      href: "https://github.com/Ptt-official-app/demo-pttbbs",
                      target: "_blank"
                    }, "Github")));
}

function MainLayout(Props) {
  var children = Props.children;
  return React.createElement(React.Fragment, undefined, React.createElement(Meta.make, {}), React.createElement("div", {
                  className: "flex lg:justify-center"
                }, React.createElement("div", {
                      className: "max-w-5xl w-full lg:w-3/4 text-gray-900 font-base"
                    }, React.createElement(MainLayout$Navigation, {}), React.createElement("main", {
                          className: "mt-4 mx-4"
                        }, children))));
}

var make = MainLayout;

export {
  make ,
  
}
/* Meta Not a pure module */
